### ISSUE TITLE
爆弾を増やす場合

### ISSUE THREAD

**Issue by c0b21005c4** [c0b21031/ProjExD#11]
https://github.com/c0b21031/ProjExD/blob/b7b0f0c538100ed3b61ee42b7d747d1c533b2ca8/ex04/dodge_bomb.py#L50
リストに格納すればすっきりとした分が書けると思います。
[[サーフェイス,レクト,x軸の動き,y軸の動き], ......]
↑のようにすればfor文で描画できると思います。

**Comment by c0b21031** [comment]
検討します
