### ISSUE TITLE
爆弾1と爆弾2の処理について

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21031/ProjExD#12]
どちらの爆弾も最後の処理がほぼ同じなので、どうせなら爆弾を作成する関数に変更してfor文で何個作るのかなどができると思います。
一番手っ取り早いのは、関数で作成した爆弾を返して、型に渡してあげるというものです
https://github.com/c0b21031/ProjExD/blob/b7b0f0c538100ed3b61ee42b7d747d1c533b2ca8/ex04/dodge_bomb.py#L40

**Comment by c0b21031** [comment]
surfaceの作り方でimageをダウンロードする場合と図形を描写する場合があったので関数でひとくくりにする方法を見つけられなかったです。もう一度考えてみます。
