### ISSUE TITLE
どうせなら

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21031/ProjExD#16]
色とか速度を変えるだけなら少し面白みがないので、回転などの設定を取り入れてみるのはどう？
https://github.com/c0b21031/ProjExD/blob/c96a848f83d799734858839afa7791d7eb678301/ex05/dodge_bomb_fsm.py#L108

**Comment by c0b21031** [comment]
bombクラスのmove_ipをいじればいけるかもしれない。検討します
