### ISSUE TITLE
この表記をするのなら

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21031/ProjExD#3]
https://github.com/c0b21031/ProjExD/blob/a6529b81b41f902138003cc200cd3be6a1d36222/ex02/calc.py#L27
元々リスト型に直して置けば処理が早くて見やすいと思う

**Comment by c0b21031** [comment]
ありがとうございます。
タプルを使用した見づらい方法でリストを初期化していました。
修正させていただきます
