### ISSUE TITLE
keyの処理について

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21031/ProjExD#6]
keyの処理(上下左右)において次の処理が壁であった場合の処理はまとめて一括で処理をすることができます。
mz = make_maze(15,9)とした時、
if key == "Up" and mz[my-1][mx] == 0:
cy -= 100
my -= 1
等のように一緒に処理してあげた方がみやすいかも(0の時は、次に進む場所が床の時)
https://github.com/c0b21031/ProjExD/blob/755f91a27ebf4bfd0720440839589c43117356a0/ex03/maze.py#L15

**Comment by c0b21031** [comment]
確かにその方が条件がまとまっていて見やすいですね。
検討します。
